
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aayus
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public MainMenu(String role) {
        initComponents();
        //System.out.println(role);
        
        setLocationRelativeTo(null);
        if (role.equals("user")){
            ManageUsers.setVisible(false);
            //adminHeader.setVisible(false);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showItems = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        ManageUsers = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showItems.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        showItems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3844476_eye_see_show_view_watch_icon.png"))); // NOI18N
        showItems.setText("Show Items");
        showItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showItemsActionPerformed(evt);
            }
        });
        getContentPane().add(showItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 30, 250, -1));

        LogOutButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LogOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit48.png"))); // NOI18N
        LogOutButton.setText("Log Out");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 970, 250, 60));

        ManageUsers.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ManageUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/285648_group_user_icon.png"))); // NOI18N
        ManageUsers.setText("Manage Users");
        ManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageUsersActionPerformed(evt);
            }
        });
        getContentPane().add(ManageUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 30, 250, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainBG1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1930, 1090));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(null, "Do you want to logout from application?", "Select", JOptionPane.YES_NO_OPTION);
        
        if (check == 0){
            setVisible(false);
            new Login().setVisible(true);
        }
        
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void ManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageUsersActionPerformed
        // TODO add your handling code here:
        new UserManagement().setVisible(true);
    }//GEN-LAST:event_ManageUsersActionPerformed

    private void showItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showItemsActionPerformed
        // TODO add your handling code here:
        new ItemManagement().setVisible(true);
    }//GEN-LAST:event_showItemsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton ManageUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton showItems;
    // End of variables declaration//GEN-END:variables
}
